import './index.scss'
export { default as Icon, IconType } from './icon'
export { default as Loading } from './loading'
export { default as Button } from './button'
export { default as Modal } from './modal'
export { default as Popover, Placement } from './popover'
export { default as Input } from './input'
export { default as Upload } from './upload'
export { default as Select, OptionType as SelectOptionType, ValueType as SelectValueType } from './select'
export { default as Tab } from './tab'
export { default as InputNumber } from './inputNumber'
export { default as InputGroup } from './inputGroup'
export { default as Switch } from './switch'
export { default as Slider } from './slider'
export { default as Collapse } from './collapse'
export { default as message, MessageType } from './message'
export { default as Checkbox, Group as CheckboxGroup } from './checkbox'
export { default as Radio, Group as RadioGroup } from './radio'
export { default as Menu, MenuItem, MenuTheme, MenuTrigger, MenuMode, MenuClick, MenuOpenChange, MenuSelect } from './menu'
export { default as Pagination, PaginationItemType } from './pagination'
export { default as Tag } from './tag'
export { default as Badge } from './badge'
export { default as Rate, RateCharacterFn } from './rate'
export { default as Carousel, CarouselDotPosition, CarouselRef, CarouselEffect } from './carousel'
export { SingleCascader as Cascader, MultipleCascader, CascaderOption, TreeMode, TreeValue } from './cascader'
export { SingleTree as Tree, MultipleTree, TreeNode } from './tree'
export { default as Table } from './table'

import { resizeListenerRegister } from './resizeListener'
import { rem2px, Rem2pxProps } from './utils'

export function responseRegister(props?: Rem2pxProps) {
  resizeListenerRegister('rem2px', (clientWidth) => rem2px(clientWidth, props), true)
}